Python pyodbc connections to IBM Netezza Erroring
